name: github_issue_tracker
description: A github issue tracker made with flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: "3.10.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: 2.3.6
  go_router: 7.0.0
  dartz: 0.10.1
  shimmer: 2.0.0
  flutter_screenutil: 5.8.4
  freezed_annotation: 2.4.1
  webview_flutter: 4.2.2
  network:
    path: network

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: 0.4.0
  riverpod_lint: 1.3.2
  freezed: 2.4.1
  build_runner: 2.4.6
  json_serializable: 6.7.1
  flutter_gen_runner: 5.3.1


analyzer:
  plugins:
    - custom_lint

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Source Code Pro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/src/core/generated
  line_length: 80

  integrations:
    flutter_svg: true